Fix/liquidation amount
astraly-labs/vesu-liquidator pull request #37
Opened 2024-08-27 12:02 UTC by azurwastaken

# Pull Request type

- Feature

## What is the current behavior?

Resolves: #31 

## What is the new behavior?

fixed computation 

## Does this introduce a breaking change?

No

## Other information

2024-08-27 14:12 UTC, akhercha requested changes
smol stuff

2024-08-27 14:12 UTC, akhercha commented on src/services/monitoring.rs
> +        println!("liquidable_amount : {}", liquidable_amount);
remove print sir

2024-08-28 07:30 UTC, azurwastaken commented on src/types/position.rs
> +    pub async fn fetch_liquidation_factors(
it seems so, as far as i saw, i'm not sure if its consistent between pools but look like it doesn't change for a given poolid/collateral/debt key. will add todo + issue

2024-08-28 07:33 UTC, azurwastaken commented on src/types/position.rs
> +        BigDecimal::new(ltv_config[0].to_bigint(), 18)
will do it but is one file for a const relevant ? 
Also, it's not related to Ethereum. I mean, maybe they choose 18 because of it but all reponse from Vesu are 18 decimal so i'll call it VESU_RESPONSE_DECIMALS instead.

2024-08-28 09:00 UTC, akhercha approved these changes
lgtm

2024-08-28 09:00 UTC, merged