feat: add ability to store current indexed data
astraly-labs/vesu-liquidator pull request #38
Opened 2024-08-28 13:31 UTC by azurwastaken

# Pull Request type

- Feature

## What is the current behavior?

Resolves: #36 

## What is the new behavior?

The bot now have a StorageTrait and a StorageWrapper that allow him to handle storage of current state (indexed position and last witnessed block by the monitoring)

currently there is only one possibility which is dumping into a json file. the service will dump every tick updated last witnessed block and positions map into the json.

At the start the run_all_service will initiate a jsonStorage that will read the json file and get the data in it. 
if there is some data he will start the indexing service from the last synced block and the monitoring service's position map will be initialized with data from the json file.
Otherwise, we do as before.

## Does this introduce a breaking change?

No

## Other information

There is many TODO's related to this but as its for an mvp it look enough to me

2024-08-28 15:04 UTC, EvolveArt requested changes

2024-08-28 15:04 UTC, EvolveArt commented on src/storage/json.rs
> +struct DataAsJson {
how is that related to Json ?

2024-08-28 15:04 UTC, EvolveArt commented on src/storage/json.rs
> +        file.write_all(json.as_bytes())?;
why do we write to json if we just write as bytes tho?

2024-08-28 15:04 UTC, EvolveArt commented on src/storage/storage_wrapper.rs
> +pub enum StorageWrapper {
remove the wrapper, we can just use the `Storage` trait

2024-08-28 15:04 UTC, EvolveArt commented on src/types/position.rs
> +    pub fn from_backup(map_backup: HashMap<u64, Position>) -> Self {
`from_storage` might be a better name, or `from_local_storage`

2024-08-28 18:12 UTC, azurwastaken commented on src/storage/storage_wrapper.rs
> +pub enum StorageWrapper {
the wrapper looked more clean and straight forward to me but done

2024-08-28 18:12 UTC, azurwastaken commented on src/types/position.rs
> +    pub fn from_backup(map_backup: HashMap<u64, Position>) -> Self {
done

2024-08-28 18:13 UTC, azurwastaken commented on src/storage/json.rs
> +        file.write_all(json.as_bytes())?;
i don't understand here, json is just a big String and we need to have it [u8] to write in file

2024-08-28 18:14 UTC, azurwastaken commented on src/storage/json.rs
> +struct DataAsJson {
it reflect json structure but maybe i can just rename it Data and put it in the storage.rs along the trait as it also represent the data we cant to store

2024-08-29 14:29 UTC, EvolveArt approved these changes

2024-08-29 14:29 UTC, merged