feat: update bindings
astraly-labs/vesu-liquidator pull request #54
Opened 2024-09-18 08:04 UTC by azurwastaken

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

Handle new version of vesu's liquidate contract

## Does this introduce a breaking change?

No

## Other information

2024-09-18 08:56 UTC, akhercha requested changes
One smol comment - also please, can we update `cainome` to 0.4.0 and fix the errors?

2024-09-18 08:56 UTC, akhercha commented on src/services/monitoring.rs
> +        let debt_to_liquidate = match self.config.liquidation_mode {
As we said, this need a little more in depth refactoring. Currently the code is shared but in a Full mode we don't need all those computation.

2024-09-19 08:51 UTC, azurwastaken commented on src/services/monitoring.rs
> +        let debt_to_liquidate = match self.config.liquidation_mode {
after further investigation, the remaining computation are needed even in Full mode

2024-09-19 08:58 UTC, akhercha commented on src/types/position.rs
>          // TODO: remove those line when vesu contract allow partial liquidation
Remove the TODO comment

2024-09-19 09:46 UTC, akhercha approved these changes
seems gud

2024-09-19 09:46 UTC, merged